#!/usr/bin/env node
// Cross-platform installer for the OM Support Assistant Claude Code bridge.
//   node bridge/install.js <EXTENSION_ID> [--kb <path>] [--all] [--quick]
//
// Runs on macOS, Linux, and Windows. Because it runs UNDER node, it uses
// process.execPath as the absolute node path for the launcher — which is what
// makes native messaging work when Chrome launches the host with a minimal PATH
// (a bare `#!/usr/bin/env node` shebang would fail under nvm/homebrew).
//
// It is self-diagnosing: it preflights node/claude/login/env, installs the host
// manifest into every Chromium-family browser it finds, then runs a live
// self-test through the launcher and prints PASS/FAIL — so a broken setup is
// caught here, with a clear message, not on someone's support call later.
//
// Linux paths and the Windows registry path are written from Chrome's docs and
// are NOT verified from this repo; the self-test is the real proof per machine.

import { existsSync, mkdirSync, writeFileSync, chmodSync, readFileSync } from "node:fs";
import { spawn, execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { createInterface } from "node:readline";

import { HOST_NAME, browserTargets, launcherName } from "./install-targets.js";
import { encodeFrame, createFrameDecoder } from "./frame-codec.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const PLATFORM = process.platform;
const BRIDGE = join(HERE, "claude-bridge.js");
const NODE = process.execPath;

const argv = process.argv.slice(2);
const flag = (name) => argv.includes(name);
const opt = (name) => {
  const i = argv.indexOf(name);
  return i !== -1 ? argv[i + 1] : undefined;
};
const positional = argv.filter((a) => !a.startsWith("--") && argv[argv.indexOf(a) - 1] !== "--kb");

const say = (s = "") => process.stdout.write(s + "\n");
const ok = (s) => say(`  ✓ ${s}`);
const warn = (s) => say(`  ⚠ ${s}`);
const fail = (s) => say(`  ✗ ${s}`);

function die(msg) {
  say("");
  fail(msg);
  say("");
  process.exit(1);
}

function ask(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => rl.question(question, (a) => { rl.close(); resolve(a.trim()); }));
}

// --- preflight ---------------------------------------------------------------
function which(bin) {
  try {
    const cmd = PLATFORM === "win32" ? "where" : "command";
    const args = PLATFORM === "win32" ? [bin] : ["-v", bin];
    const out = execFileSync(cmd, args, { encoding: "utf8", shell: PLATFORM === "win32" });
    return out.split(/\r?\n/).filter(Boolean)[0] || "";
  } catch {
    return "";
  }
}

function loadConfig() {
  const p = join(HERE, "config.json");
  if (!existsSync(p)) return {};
  try { return JSON.parse(readFileSync(p, "utf8")); } catch { return {}; }
}

function resolveClaude(config) {
  if (config.claudeBin && existsSync(config.claudeBin)) return config.claudeBin;
  return which("claude");
}

function checkLogin(claudeBin) {
  try {
    const out = execFileSync(claudeBin, ["auth", "status"], { encoding: "utf8" });
    let loggedIn, provider, org;
    try {
      const j = JSON.parse(out);
      loggedIn = j.loggedIn; provider = j.apiProvider; org = j.orgName;
    } catch {
      loggedIn = /logged\s*in|"loggedIn"\s*:\s*true/i.test(out);
    }
    return { loggedIn: !!loggedIn, provider, org, raw: out.trim() };
  } catch (e) {
    return { loggedIn: false, error: e.message };
  }
}

// --- artifacts ---------------------------------------------------------------
function writeLauncher() {
  const path = join(HERE, launcherName(PLATFORM));
  if (PLATFORM === "win32") {
    writeFileSync(path, `@echo off\r\n"${NODE}" "${BRIDGE}" %*\r\n`);
  } else {
    writeFileSync(path, `#!/bin/sh\n# Machine-local launcher (gitignored) — regenerated by install.js.\nexec "${NODE}" "${BRIDGE}" "$@"\n`);
    chmodSync(path, 0o755);
    chmodSync(BRIDGE, 0o755);
  }
  return path;
}

function manifestObject(launcherPath, extId) {
  return {
    name: HOST_NAME,
    description: "OM Support Assistant — Claude Code native-messaging bridge",
    type: "stdio",
    path: launcherPath,
    allowed_origins: [`chrome-extension://${extId}/`],
  };
}

function installManifests(launcherPath, extId, all) {
  const json = JSON.stringify(manifestObject(launcherPath, extId), null, 2);
  const installed = [];

  if (PLATFORM === "win32") {
    const manifestPath = join(HERE, "host-manifest.win.json");
    writeFileSync(manifestPath, json);
    for (const t of browserTargets(PLATFORM, homedir())) {
      try {
        execFileSync("reg", ["add", `HKCU\\${t.regKey}\\${HOST_NAME}`, "/ve", "/t", "REG_SZ", "/d", manifestPath, "/f"], { stdio: "ignore" });
        installed.push(t.name);
      } catch {
        warn(`could not set registry key for ${t.name}`);
      }
    }
    return installed;
  }

  for (const t of browserTargets(PLATFORM, homedir())) {
    if (!all && !existsSync(t.baseDir)) continue; // browser not installed
    try {
      mkdirSync(t.manifestDir, { recursive: true });
      writeFileSync(join(t.manifestDir, `${HOST_NAME}.json`), json);
      installed.push(t.name);
    } catch (e) {
      warn(`could not install for ${t.name}: ${e.message}`);
    }
  }
  return installed;
}

// --- live self-test through the launcher -------------------------------------
function selfTest(launcherPath, { transform }) {
  return new Promise((resolve) => {
    const reqs = [{ ping: true }];
    if (transform) reqs.push({ system: "Reply with exactly: OK", user: "ping", mode: "transform" });
    // Minimal env, like Chrome gives a native host, to catch PATH/login issues now.
    const env = { HOME: process.env.HOME, USERPROFILE: process.env.USERPROFILE, PATH: PLATFORM === "win32" ? process.env.PATH : "/usr/bin:/bin" };
    const child = spawn(launcherPath, [], { stdio: ["pipe", "pipe", "pipe"], env });
    const dec = createFrameDecoder();
    const replies = [];
    let stderr = "";
    child.stdout.on("data", (c) => { for (const r of dec.push(c)) replies.push(r); });
    child.stderr.on("data", (d) => (stderr += d));
    child.on("error", (e) => resolve({ pingOk: false, error: e.message }));
    child.on("close", () => {
      const ping = replies.find((r) => r.pong);
      const tx = replies.find((r) => "text" in r);
      resolve({
        pingOk: !!(ping && ping.ok),
        kb: !!(ping && ping.kb),
        transformOk: transform ? !!(tx && tx.text && !tx.error) : null,
        transformText: tx?.text,
        transformError: tx?.error,
        stderr: stderr.trim(),
      });
    });
    for (const r of reqs) child.stdin.write(encodeFrame(r));
    child.stdin.end();
  });
}

// --- main --------------------------------------------------------------------
async function main() {
  say("OM Support Assistant — Claude Code bridge installer");
  say(`Platform: ${PLATFORM} | node: ${NODE}`);
  say(`Bridge:   ${BRIDGE}`);
  say("");

  say("Preflight:");
  if (!existsSync(BRIDGE)) die(`bridge not found at ${BRIDGE}`);
  ok(`node ${process.version}`);

  const config = loadConfig();
  const claudeBin = resolveClaude(config);
  if (!claudeBin) {
    die("`claude` not found. Install Claude Code and log in to your Enterprise seat, then re-run.\n    macOS/Linux: https://claude.com/code");
  }
  ok(`claude: ${claudeBin}`);

  const login = checkLogin(claudeBin);
  if (!login.loggedIn) {
    warn(`claude is NOT logged in (\`claude auth status\` failed or shows logged out).`);
    warn(`Run \`claude auth login\` (Enterprise seat) — the bridge will fail until you do.`);
  } else {
    ok(`logged in${login.org ? ` (${login.org})` : ""}${login.provider ? `, ${login.provider}` : ""}`);
    if (login.provider && login.provider !== "firstParty") {
      warn(`auth provider is "${login.provider}", not "firstParty" — data may not route through the Enterprise seat.`);
    }
  }
  if (process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN) {
    warn(`ANTHROPIC_API_KEY/ANTHROPIC_AUTH_TOKEN is set in your shell. The bridge strips it (so it still uses the Enterprise seat), but unset it if you also use \`claude\` interactively and want the seat there too.`);
  }

  // config.json
  const configPath = join(HERE, "config.json");
  if (!existsSync(configPath)) {
    const kb = opt("--kb") || (process.stdin.isTTY ? await ask("Path to your support-desk KB (optional, blank to skip): ") : "");
    const obj = { claudeBin };
    if (kb) obj.kbRoot = kb;
    writeFileSync(configPath, JSON.stringify(obj, null, 2) + "\n");
    ok(`wrote config.json`);
  } else {
    ok(`config.json exists (left untouched)`);
  }

  // extension id
  let extId = positional[0] || opt("--id");
  if (!extId) extId = await ask("Unpacked extension ID (chrome://extensions → Developer mode): ");
  if (!/^[a-p]{32}$/.test(extId)) {
    if (!extId) die("extension ID is required.");
    warn(`"${extId}" doesn't look like a 32-char extension ID — continuing anyway.`);
  }

  say("");
  say("Installing:");
  const launcherPath = writeLauncher();
  ok(`launcher: ${launcherPath}`);
  const installed = installManifests(launcherPath, extId, flag("--all"));
  if (!installed.length) {
    die("No Chromium-family browser detected. Install one, or re-run with --all to write manifests for every supported browser regardless.");
  }
  for (const name of installed) ok(`manifest → ${name}`);

  say("");
  say("Self-test (through the launcher, minimal env like Chrome):");
  const result = await selfTest(launcherPath, { transform: !flag("--quick") });
  if (!result.pingOk) {
    fail(`ping failed. ${result.error || result.stderr || "(no detail)"}`);
    die("The bridge could not start. Check the node/claude paths above.");
  }
  ok(`ping ok (knowledge base ${result.kb ? "detected" : "not configured"})`);
  if (result.transformOk === false) {
    fail(`transform failed: ${result.transformError || result.stderr || "(no detail)"}`);
    warn(`Common cause: claude not logged in, or login not visible to a spawned process.`);
    die("Bridge starts but claude call failed — fix the above before using the extension.");
  }
  if (result.transformOk) ok(`transform ok (claude replied: ${JSON.stringify(result.transformText)})`);

  say("");
  say("✅ Done. Next steps:");
  say(`  1. Load the unpacked extension in each browser you use (chrome://extensions → Developer mode → Load unpacked → this repo).`);
  say(`     The extension ID must match what you gave here (${extId}); the ID is derived from the folder path, so it's the same across browsers.`);
  say(`  2. After changing manifest.json permissions, reload the extension.`);
  if (PLATFORM === "darwin") {
    say("");
    say("  macOS note: the first time a call runs, macOS may show a one-time notice about");
    say('  "ripgrep.node" ("could not verify free of malware"). That is Claude Code\'s bundled');
    say("  search engine (ad-hoc signed), not this extension. Click Done, then allow it in");
    say("  System Settings → Privacy & Security → “Allow Anyway”. See bridge/README.md.");
  }
  say("");
}

main().catch((e) => die(e.stack || e.message));
