// Pure helpers for the macOS launchd agent that hosts the bridge daemon.
// No fs, no exec — string/path construction only, so it's unit-testable.
//
// Why a launchd agent at all: files created by a browser-descended process tree
// get com.apple.quarantine (Gatekeeper popups for claude's extracted
// ripgrep.node, with a random filename each run so "Allow Anyway" can never
// stick — approval is per-file). A launchd-launched daemon is outside that
// tree, so the files stay clean. Design adversarially reviewed 2026-07-10;
// see bridge/README.md and DECISIONS D41.

import { homedir } from "node:os";
import { join } from "node:path";

export const AGENT_LABEL = "com.optinmonster.claude_bridge_daemon";

export function daemonDir(home = homedir()) {
  return join(home, ".om-claude-bridge");
}

// Unix socket path — keep it short (macOS caps sun_path at 104 bytes).
export function socketPath(home = homedir()) {
  return join(daemonDir(home), "bridge.sock");
}

export function daemonLogPath(home = homedir()) {
  return join(daemonDir(home), "daemon.log");
}

// Machine-local /bin/sh launcher, generated by install.js. The plist points at
// THIS (via /bin/sh) instead of an absolute node path because nvm/homebrew node
// paths vanish on version bumps — launchd would then crash-loop the agent and
// the forwarder's silent fallback would quietly bring the popups back. The
// launcher re-resolves node at every start.
export function daemonLauncherPath(home = homedir()) {
  return join(daemonDir(home), "daemon-launch.sh");
}

export function plistPath(home = homedir()) {
  return join(home, "Library", "LaunchAgents", `${AGENT_LABEL}.plist`);
}

const shQuote = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;

// The launcher script body. Resolution order for node:
// 1. the absolute path captured at install time (fast path),
// 2. whatever `command -v node` finds with common install dirs appended,
// 3. the newest ~/.nvm/versions/node/*/bin/node.
export function buildDaemonLauncher({ nodePath, daemonPath, home }) {
  return `#!/bin/sh
# Machine-local launcher (generated by bridge/install.js — re-run it to update).
# Re-resolves node at every start so nvm/homebrew version bumps don't kill the
# daemon (a dead daemon silently brings the Gatekeeper popups back).
NODE=${shQuote(nodePath)}
if [ ! -x "$NODE" ]; then
  PATH="$PATH:/opt/homebrew/bin:/usr/local/bin:${home}/.local/bin"
  NODE="$(command -v node 2>/dev/null)"
fi
if [ ! -x "$NODE" ]; then
  for c in "${home}"/.nvm/versions/node/*/bin/node; do
    [ -x "$c" ] && NODE="$c"
  done
fi
if [ ! -x "$NODE" ]; then
  echo "[daemon-launch] no node found; re-run bridge/install.js" >&2
  exit 1
fi
exec "$NODE" ${shQuote(daemonPath)}
`;
}

const xmlEscape = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// The agent plist. Notes:
// - ProgramArguments goes through /bin/sh + the launcher (node re-resolution).
// - KeepAlive.SuccessfulExit=false: restart on crash, but a clean exit(0)
//   (e.g. "another instance already owns the socket") stays down instead of
//   flap-looping.
// - ThrottleInterval softens any crash loop.
export function buildPlist({ launcherPath, logPath }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${AGENT_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${xmlEscape(launcherPath)}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>${xmlEscape(logPath)}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(logPath)}</string>
</dict>
</plist>
`;
}

// launchctl invocations (argv arrays, ready for execFileSync).
export function launchctlEnable(uid) {
  return ["launchctl", "enable", `gui/${uid}/${AGENT_LABEL}`];
}

export function launchctlBootout(uid) {
  return ["launchctl", "bootout", `gui/${uid}/${AGENT_LABEL}`];
}

export function launchctlBootstrap(uid, plist) {
  return ["launchctl", "bootstrap", `gui/${uid}`, plist];
}

export function launchctlPrint(uid) {
  return ["launchctl", "print", `gui/${uid}/${AGENT_LABEL}`];
}

export function launchctlKickstart(uid) {
  return ["launchctl", "kickstart", "-k", `gui/${uid}/${AGENT_LABEL}`];
}
